def imprime(var1, var2):
    print("<!DOCTYPE html>")
    print("<html lang=\"pt-br\">")
    print("<head>")
    print("    <meta charset=\"UTF-8\">")
    print("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">")
    print("    <title>Executando Python em um Web Server</title>")
    print("</head>")
    print("<body>")
    print("    <h1>Executando Python em um Web Server</h1>")
    print("    <h3>A palavra %s tem %i letras!</h3>" % (var1, var2))
    print("</body>")
    print("</html>")